// 从 coloros-ui-kit 978d318 的 web/tokens.g.ts 同步，不要手改；运行 yarn sync:coloros-tokens 更新。
// 由 tools/gen_tokens.py 从 tokens/coloros17.json 生成，不要手改。
// dp/sp 为逻辑像素；px 为物理像素，使用时除以设备像素比；颜色为 #RRGGBBAA；混合模式为 CSS mix-blend-mode 名称。

export const CoTokens = {
  meta: {
    coloros: "V17.0.0 (PJZ110, Android 17)",
    coui: "Gallery 17.9.24 / Clock 17.6.70",
  },
  color: {
    primary: { light: '#0080FFFF', dark: '#1A8CFFFF' },
    primaryText: { light: '#0080FFFF', dark: '#5C9DFFFF' },
    primaryContainer: { light: '#0080FF26', dark: '#1A8CFF40' },
    primaryDisabled: { light: '#0080FF4D', dark: '#1A8CFF4D' },
    focus: { light: '#0080FF1F', dark: '#1A8CFF33' },
    focusOutline: { light: '#0080FF66', dark: '#5C9DFF66' },
    onPrimary: { light: '#FFFFFFFF', dark: '#FFFFFFFF' },
    label1: { light: '#000000E6', dark: '#FFFFFFE6' },
    label1Variant: { light: '#000000B8', dark: '#FFFFFFB8' },
    label2: { light: '#0000008A', dark: '#FFFFFF8A' },
    label2Variant: { light: '#00000066', dark: '#FFFFFF66' },
    label3: { light: '#00000042', dark: '#FFFFFF4D' },
    label4: { light: '#00000014', dark: '#FFFFFF26' },
    bg: { light: '#FFFFFFFF', dark: '#000000FF' },
    bgGrouped: { light: '#F0F1F2FF', dark: '#000000FF' },
    surface: { light: '#FFFFFFFF', dark: '#1E1E1EFF' },
    surfaceGrouped: { light: '#F0F1F2FF', dark: '#1E1E1EFF' },
    surfaceTop: { light: '#FFFFFFFF', dark: '#333333FF' },
    bar: { light: '#FAFAFAFF', dark: '#1E1E1EFF' },
    card: { light: '#FFFFFFFF', dark: '#FFFFFF1A' },
    cardPressed: { light: '#E6E6E6FF', dark: '#FFFFFF33' },
    fill4: { light: '#0000000A', dark: '#FFFFFF1A' },
    fill8: { light: '#00000014', dark: '#FFFFFF1A' },
    fill12: { light: '#0000001F', dark: '#FFFFFF33' },
    fill16: { light: '#00000029', dark: '#FFFFFF40' },
    fillSolid: { light: '#EBEBEBFF', dark: '#262626FF' },
    controlTrack: { light: '#00000029', dark: '#FFFFFF40' },
    divider: { light: '#0000001F', dark: '#FFFFFF33' },
    press: { light: '#0000001F', dark: '#FFFFFF33' },
    hover: { light: '#00000014', dark: '#FFFFFF26' },
    scrim: { light: '#00000033', dark: '#00000099' },
    error: { light: '#DB382CFF', dark: '#FF6C61FF' },
    success: { light: '#00BD13FF', dark: '#24B232FF' },
  },
  themeColor: {
    orange: {
      primary: { light: '#FF7700FF', dark: '#F08222FF' },
      primaryText: { light: '#EB6E00FF', dark: '#F08222FF' },
      primaryContainer: { light: '#FF770026', dark: '#F0822240' },
      primaryDisabled: { light: '#FF77004D', dark: '#F0822266' },
      focus: { light: '#FF77001F', dark: '#F0822233' },
      focusOutline: { light: '#EB6E0066', dark: '#F0822266' },
    },
  },
  type: {
    displayL: { size: 72, lineHeight: 96, weight: 400 },
    displayM: { size: 36, lineHeight: 50, weight: 600 },
    displayS: { size: 32, lineHeight: 46, weight: 600 },
    displayXS: { size: 24, lineHeight: 34, weight: 600 },
    headlineL: { size: 28, lineHeight: 40, weight: 500 },
    headlineM: { size: 20, lineHeight: 28, weight: 500 },
    headlineS: { size: 18, lineHeight: 24, weight: 550 },
    headlineXS: { size: 16, lineHeight: 22, weight: 500 },
    bodyXL: { size: 16, lineHeight: 22, weight: 400 },
    bodyL: { size: 15, lineHeight: 20, weight: 400 },
    bodyM: { size: 14, lineHeight: 20, weight: 400 },
    bodyS: { size: 13, lineHeight: 18, weight: 400 },
    bodyXS: { size: 12, lineHeight: 16, weight: 400 },
    buttonL: { size: 16, lineHeight: 22, weight: 400 },
    buttonM: { size: 14, lineHeight: 20, weight: 500 },
    buttonS: { size: 12, lineHeight: 16, weight: 500 },
    caption: { size: 10, lineHeight: 14, weight: 400 },
    tag: { size: 10, lineHeight: 14, weight: 500 },
  },
  radius: {
    xs: 4,
    s: 8,
    m: 12,
    l: 16,
    xl: 20,
    xxl: 24,
    xxxl: 28,
    xxxxl: 32,
    full: 72,
    weightCapsule: 1,
    weightCircle: 2,
    weightCustom: 3,
  },
  shadow: {
    causticDown: {
      elevation: 24,
      alpha: 45,
      lightY: -320,
      lightZ: 0,
      lightR: 1600,
    },
    causticUpper: {
      elevation: 16,
      alpha: 30,
      lightY: -160,
      lightZ: 0,
      lightR: 800,
    },
    fallbackLevel2: {
      elevation: 12,
      color: '#0000008A',
    },
  },
  caustic: {
    color1: { light: '#FFFFFF2E', dark: '#FFFFFF33' },
    color2: { light: '#FFFFFF42', dark: '#FFFFFF42' },
    factor0: 0.6,
    factor1: 0.6,
    speed: 18,
    lumThreshold: 0.45,
    lumIntensity: 0.6,
    level2: {
      bottom: 4.9,
      sdf: 9.23,
    },
    level3: {
      bottom: 4.9,
      sdf: 10.4,
    },
    level4: {
      bottom: 4.9,
      sdf: 10.4,
    },
    level5: {
      bottom: 11.2,
      sdf: 20,
    },
    softPeak: 0.42,
  },
  material: {
    topBar: {
      radius: 0,
      c1: { light: '#33333366', dark: '#262626CC' },
      m1: { light: 'color-dodge', dark: 'normal' },
      c2: { light: '#F5F5F599', dark: '#7F7F7FB3' },
      m2: { light: 'luminosity', dark: 'overlay' },
    },
    topBarBlur: {
      radius: 50,
      alpha: { light: 0.8, dark: 0.6 },
      gradientStart: 30,
      gradientEnd: 0,
      gradientSpeed: 3,
      gradientMidPos: 0.4,
      gradientMidAlpha: 0.7,
      gradientTopAlpha: { light: 1, dark: 0.4 },
      extraHeight: 24,
    },
    bottomBar: {
      radius: 25,
      c1: { light: '#666666B3', dark: '#66666680' },
      m1: { light: 'color-dodge', dark: 'overlay' },
      c2: { light: '#F5F5F599', dark: '#262626B3' },
      m2: { light: 'luminosity', dark: 'luminosity' },
    },
    secondaryButton: {
      radius: 25,
      c1: { light: '#FFFFFFCC', dark: '#FFFFFF33' },
      m1: { light: 'normal', dark: 'normal' },
      c2: { light: '#FFFFFF00', dark: '#FFFFFF00' },
      m2: { light: 'normal', dark: 'normal' },
    },
    transparentButton: {
      radius: 25,
      c1: { light: '#3333333F', dark: '#3333333F' },
      m1: { light: 'overlay', dark: 'overlay' },
      c2: { light: '#FFFFFF3F', dark: '#FFFFFF3F' },
      m2: { light: 'luminosity', dark: 'luminosity' },
    },
    fab: {
      radius: 10,
      disabledAlpha1: 77,
      disabledC2: '#FFFFFF19',
      alpha1: { light: 229, dark: 230 },
      c2: { light: '#FFFFFF1A', dark: '#FFFFFF19' },
      m2: { light: 'overlay', dark: 'overlay' },
    },
    primaryButton: {
      radius: 10,
      disabledAlpha1: 77,
      disabledC2: '#FFFFFF19',
      alpha1: { light: 229, dark: 230 },
      c2: { light: '#FFFFFF00', dark: '#FFFFFF19' },
      m2: { light: 'overlay', dark: 'overlay' },
    },
    stroke: {
      capsule1: {
        edgeAlpha: { light: 0.2, dark: 0.6 },
        edgeWidth: { light: 2.2, dark: 2.2 },
        fadeIn: { light: 0.1, dark: 0.01 },
        fadeOut: { light: 1, dark: 1 },
        fadeScale: { light: 1.15, dark: 1 },
      },
      circle2: {
        edgeAlpha: { light: 0.25, dark: 0.25 },
        edgeWidth: { light: 2.5, dark: 2.5 },
        fadeIn: { light: 0.3, dark: 0.3 },
        fadeOut: { light: 1, dark: 1 },
        fadeScale: { light: 1, dark: 1 },
      },
      circle1: {
        edgeAlpha: { light: 0.2, dark: 0.6 },
        edgeWidth: { light: 1.9, dark: 1.9 },
        fadeIn: { light: 0.15, dark: 0.1 },
        fadeOut: { light: 1, dark: 1 },
        fadeScale: { light: 1, dark: 1 },
      },
      capsule3: {
        edgeAlpha: { light: 0.25, dark: 0.8 },
        edgeWidth: { light: 2.5, dark: 2.5 },
        fadeIn: { light: 0.1, dark: 0.03 },
        fadeOut: { light: 1, dark: 1 },
        fadeScale: { light: 1, dark: 1 },
      },
      contentCapsule1: {
        edgeAlpha: { light: 0.3, dark: 0.26 },
        edgeWidth: { light: 2.8, dark: 2.8 },
        fadeIn: { light: 0.1, dark: 0.08 },
        fadeOut: { light: 1, dark: 1 },
        fadeScale: { light: 1, dark: 0.8 },
      },
      contentCapsule2: {
        edgeAlpha: { light: 0.5, dark: 0.5 },
        edgeWidth: { light: 2.8, dark: 2.8 },
        fadeIn: { light: 0.1, dark: 0.05 },
        fadeOut: { light: 1, dark: 1 },
        fadeScale: { light: 1, dark: 1 },
      },
      contentCapsule3: {
        edgeAlpha: { light: 0.5, dark: 0.5 },
        edgeWidth: { light: 2.8, dark: 2.8 },
        fadeIn: { light: 0.05, dark: 0.05 },
        fadeOut: { light: 1, dark: 1 },
        fadeScale: { light: 1, dark: 1 },
      },
    },
    dialogWindow: {
      blurRadius: 200,
      blurType: 2,
      cornerWeight: 3,
      mode: { light: 3, dark: 2 },
      blend: { light: '#9F9F9F50', dark: '#292929B2' },
      mix: { light: '#909090DC', dark: '#7777778C' },
    },
    popupWindow: {
      blurRadius: 160,
      blurType: 2,
      cornerWeight: 2.5,
      mode: { light: 4, dark: 4 },
      blend: { light: '#EEEEEEBF', dark: '#26262699' },
      mix: { light: '#CDCDCD99', dark: '#26262699' },
    },
    panelWindow: {
      blurRadius: 400,
      blurType: 2,
      cornerWeight: 3,
      mode: { light: 3, dark: 2 },
      blend: { light: '#6E6E6E37', dark: '#0F0F0FB3' },
      mix: { light: '#C8C8C8DC', dark: '#515151A4' },
    },
    shadowEdge: {
      edge0: {
        refW: 400,
        refH: 100,
        nearSolid: 2,
        nearFade: 6,
        farSolid: 2,
        farFade: 3,
        alphaNear: 0.7,
        alphaFar: 1,
        nearFull: 0.2,
        nearTail: 0.4,
        farFull: 0.15,
        farTail: 0.35,
      },
      edge1: {
        refW: 160,
        refH: 160,
        nearSolid: 2,
        nearFade: 6,
        farSolid: 2,
        farFade: 3,
        alphaNear: 0.7,
        alphaFar: 1,
        nearFull: 0.06,
        nearTail: 0.4,
        farFull: 0.01,
        farTail: 0.28,
      },
      edge2: {
        refW: 600,
        refH: 200,
        nearSolid: 2,
        nearFade: 8,
        farSolid: 2,
        farFade: 2,
        alphaNear: 0.7,
        alphaFar: 0.6,
        nearFull: 0.18,
        nearTail: 0.35,
        farFull: 0.25,
        farTail: 0.25,
      },
      glow0: {
        refW: 400,
        refH: 100,
        alpha: 1,
        offsetY: 20,
        scaleX: 1.3,
        scaleY: 1.15,
        fadeIn: 120,
        curveMix: 0.9,
      },
      glow1: {
        refW: 160,
        refH: 160,
        alpha: 0.4,
        offsetY: 20,
        scaleX: 1.4,
        scaleY: 1.35,
        fadeIn: 140,
        curveMix: 0.9,
      },
      glow2: {
        refW: 600,
        refH: 600,
        alpha: 0.6,
        offsetY: 10,
        scaleX: 1.1,
        scaleY: 1.07,
        fadeIn: 86,
        curveMix: 0.7,
      },
    },
    softStroke: {
      capsule12: {
        edgeAlpha: { light: 0.8, dark: 0.15 },
        edgeWidth: { light: 2, dark: 2 },
        fadeIn: { light: 0.1, dark: 0.01 },
        fadeScale: { light: 1, dark: 1 },
      },
      capsule8: {
        edgeAlpha: { light: 0.8, dark: 0.15 },
        edgeWidth: { light: 1.8, dark: 1.8 },
        fadeIn: { light: 0.1, dark: 0.01 },
        fadeScale: { light: 1, dark: 1 },
      },
      circle4: {
        edgeAlpha: { light: 0.8, dark: 0.15 },
        edgeWidth: { light: 1.8, dark: 1.8 },
        fadeIn: { light: 0.1, dark: 0.01 },
        fadeScale: { light: 1, dark: 1 },
      },
      content4: {
        edgeAlpha: { light: 0.3, dark: 0.25 },
        edgeWidth: { light: 2.5, dark: 2.5 },
        fadeIn: { light: 0.1, dark: 0.1 },
        fadeScale: { light: 1, dark: 1 },
      },
      content4Disabled: {
        edgeAlpha: { light: 0.3, dark: 0.05 },
        edgeWidth: { light: 2.5, dark: 2.5 },
        fadeIn: { light: 0.04, dark: 0.06 },
        fadeScale: { light: 1, dark: 1 },
      },
      content5: {
        edgeAlpha: { light: 0.8, dark: 0.1 },
        edgeWidth: { light: 3, dark: 3 },
        fadeIn: { light: 0.05, dark: 0.01 },
        fadeScale: { light: 1, dark: 1 },
      },
      content5Disabled: {
        edgeAlpha: { light: 0.24, dark: 0.03 },
        edgeWidth: { light: 3, dark: 3 },
        fadeIn: { light: 0.05, dark: 0.01 },
        fadeScale: { light: 1, dark: 1 },
      },
      content6: {
        edgeAlpha: { light: 0.5, dark: 0.15 },
        edgeWidth: { light: 3, dark: 3 },
        fadeIn: { light: 0.01, dark: 0.01 },
        fadeScale: { light: 1, dark: 1 },
      },
      content6Disabled: {
        edgeAlpha: { light: 0.15, dark: 0.045 },
        edgeWidth: { light: 3, dark: 3 },
        fadeIn: { light: 0.01, dark: 0.01 },
        fadeScale: { light: 1, dark: 1 },
      },
    },
    windowEdge: {
      dialog: {
        edgeAlpha: { light: 0.6, dark: 0.3 },
        edgeWidth: { light: 4, dark: 2 },
        fadeIn: { light: 0.4, dark: 0.03 },
        fadeScale: { light: 1, dark: 1 },
      },
      panel: {
        edgeAlpha: { light: 0.8, dark: 0.15 },
        edgeWidth: { light: 4, dark: 2 },
        fadeIn: { light: 0.4, dark: 0.1 },
        fadeScale: { light: 1, dark: 1 },
      },
      popup: {
        edgeAlpha: { light: 0.9, dark: 0.4 },
        edgeWidth: { light: 4, dark: 2 },
        fadeIn: { light: 0.9, dark: 0.1 },
        fadeScale: { light: 1, dark: 1 },
      },
    },
  },
  spotlight: {
    glow: { bounce: 0, response: 0.15 },
    extinguish: { bounce: 0, response: 0.4 },
    follow: { bounce: 0.15, response: 0.35 },
    opaqueMedium2: {
      radiusStart: 100,
      radiusEnd: 500,
      lightHeight: 200,
      ambient: 0.4,
      diffuse: 0.4,
      noise: 0.08,
      blend: { light: 'overlay', dark: 'plus-lighter' },
      intensity: { light: 1, dark: 0.15 },
    },
    opaqueMedium1: {
      radiusStart: 100,
      radiusEnd: 500,
      lightHeight: 200,
      ambient: 0.4,
      diffuse: 0.4,
      noise: 0.08,
      blend: { light: 'overlay', dark: 'overlay' },
      intensity: { light: 0.6, dark: 0.8 },
    },
    transparentMedium1: {
      radiusStart: 100,
      radiusEnd: 500,
      lightHeight: 200,
      ambient: 0.4,
      diffuse: 0.4,
      noise: 0.08,
      blend: { light: 'overlay', dark: 'overlay' },
      intensity: { light: 0.5, dark: 0.3 },
    },
  },
  touchMotion: {
    deadZone: 5,
    rubberMax: 28,
    rubberCoef: 0.05,
    deformMax: 1.2,
    deformK1: 350000,
    deformK2: 15,
    deformMinArea: 38416,
    deformDist: 150,
    deformCoef: 0.55,
    pressAreaMin: 20,
    pressAreaMax: 150,
    pressScaleMin: 0.85,
    pressScaleMax: 0.97,
    pressAspectMin: 2,
    pressAspectMax: 15,
    pressAspectScaleMax: 1,
    follow: { bounce: 0.15, response: 0.15 },
    candyPress: { bounce: 0, response: 0.3 },
    candyRelease: { bounce: 0.5, response: 0.5 },
    jellyPress: { bounce: 0, response: 0.25 },
    jellyRelease: { bounce: 0.6, response: 0.5 },
    handUpBounce: 0.65,
    handUpResponseSmall: 0.42,
    handUpResponseLarge: 0.45,
    handUpAreaSmall: 56,
    handUpAreaLarge: 100,
    deformSnap: 0.002,
  },
  floatingNavBar: {
    height: 56,
    padding: 12,
    itemSpacing: 8,
    itemMaxWidth: 70,
    itemHeight: 48,
    iconSize: 24,
    iconTop: 4,
    titleGap: 2,
    titleSize: 10,
    titleWeight: 500,
    barPaddingH: 16,
    barPaddingTop: 16,
    toNavBar: 8,
    accessorySize: 56,
    accessoryGap: 12,
    iconFadeIn: 200,
    iconFadeOut: 100,
    showAlpha: { bounce: 0, response: 0.2 },
    showScale: { bounce: 0.35, response: 0.35 },
    hiddenScale: 0.8,
    resize: { bounce: 0.35, response: 0.55 },
    editSingleItemMaxWidth: 148,
    editShow: { bounce: 0.25, response: 0.38 },
  },
  switch: {
    width: 44,
    height: 24,
    thumbSize: 18,
    thumbPadding: 3,
    thumbShadowRadius: 2,
    thumbShadowDy: 1,
    thumbShadowColor: '#00000019',
    thumb: '#FFFFFFFF',
    thumbDisabled: { light: '#FFFFFF8A', dark: '#FFFFFF29' },
    stretchMax: 1.3,
    stretchPeak: 0.3473,
    toggle: { bounce: 0.3, response: 0.4 },
    dragFollow: { bounce: 0, response: 0.3 },
    dragSnap: { bounce: 0.2, response: 0.4 },
    pressMask: { bounce: 0, response: 0.3 },
    flingVelocity: 250,
    flingMinDistance: 1,
    disabledOnAlpha: 77,
  },
  button: {
    drawableSecondaryBg: { light: '#FFFFFFA6', dark: '#FFFFFF33' },
    drawableTransparentBg: { light: '#FFFFFF33', dark: '#FFFFFF19' },
    largeHeight: 44,
    largeMinWidth: 132,
    largePaddingH: 12,
    largePaddingV: 8,
    smallHeight: 28,
    smallMinWidth: 52,
    smallPaddingH: 12,
    smallPaddingV: 4,
    largeText: { size: 16, lineHeight: 19.2, weight: 500 },
    smallText: { size: 14, lineHeight: 15.4, weight: 500 },
    fontScaleMax: 1.35,
    disabledAlpha: 77,
    secondaryBg: { light: '#EBEBEBFF', dark: '#343434FF' },
    secondaryDisabledBg: { light: '#00000014', dark: '#FFFFFF1A' },
    transparentBg: '#FFFFFF33',
    onPrimaryDisabled: { light: '#FFFFFF8A', dark: '#FFFFFF28' },
    secondaryTextDisabled: { light: '#00000042', dark: '#FFFFFF28' },
    transparentTextDisabled: '#FFFFFF4D',
    pressMask: { bounce: 0, response: 0.3 },
    pressMaskMinProgress: 0.7,
  },
  dialog: {
    maxWidth: 360,
    insetH: 16,
    insetBottom: 32,
    maxHeight: 600,
    cornerRadius: 45,
    cornerRadiusNoSmooth: 32,
    cornerWeight: 3,
    dim: { light: 0.2, dark: 0.6 },
    titleSize: 18,
    titleLineHeight: 24,
    titleWeight: 600,
    titleTop: 24,
    titleBottom: 6,
    paddingH: 24,
    messageSize: 13,
    messageLineHeight: 18,
    messageBottom: 16,
    buttonBarH: 16,
    buttonGap: 4,
    buttonBarTop: 4,
    buttonBarBottom: 16,
    buttonMinHeight: 44,
    buttonTextColor: { light: '#0080FFFF', dark: '#5C9DFFFF' },
    buttonTextDanger: { light: '#DB382CFF', dark: '#FF6C61FF' },
    enterDuration: 250,
    exitDurationCenter: 150,
    exitDurationBottom: 250,
    enterScale: 0.8,
  },
  popupMenu: {
    minWidth: 168,
    maxWidth: 256,
    iconWidth: 196,
    itemMinHeight: 40,
    itemPaddingV: 8,
    itemPaddingH: 20,
    iconSize: 20,
    textSize: 16,
    listPaddingV: 8,
    cornerRadius: 28,
    cornerWeight: 2.5,
    anchorGap: 8,
    screenMarginTop: 16,
    screenMarginBottom: 32,
    fallbackElevation: 30,
    enterPath: { bounce: 0.13, response: 0.29 },
    enterScale: { bounce: 0.2, response: 0.4 },
    enterAlpha: { bounce: 0, response: 0.27 },
    exitPath: { bounce: 0, response: 0.26 },
    exitScale: { bounce: 0, response: 0.21 },
    exitAlpha: { bounce: 0, response: 0.23 },
  },
  list: {
    overscrollGain: 0.4,
    overscrollRelease: { bounce: -0.3, response: 0.4336 },
    cardMarginH: 16,
    cardRadius: 24,
    cardRadiusNoSmooth: 20,
    cardWeight: 2.5,
    edgePadding: 2,
    itemMinHeight: 48,
    paddingH: 16,
    paddingV: 10,
    title: { size: 16, lineHeight: 21, weight: 500 },
    summary: { size: 13, lineHeight: 18, weight: 400 },
    iconPaddingV: 14,
    iconGap: 16,
    statusSize: 14,
    statusMaxWidth: 162,
    statusGap: 24,
    arrowWidth: 12,
    arrowHeight: 24,
    menuArrowWidth: 14,
    arrowStroke: 1.4,
    arrowGap: 4,
    switchGap: 16,
    divider: 0.33,
    pressMask: { bounce: 0, response: 0.3 },
    pressMaskMinProgress: 0.7,
    categorySize: 12,
    categoryLineHeight: 16,
    categoryWeight: 500,
    categoryMarginV: 8,
    categoryIndent: 32,
    groupTop: 16,
    listBottomPadding: 32,
  },
  emptyState: {
    imageWidth: 120,
    imageHeight: 100,
    imageMinContainer: 200,
    titleMaxWidth: 280,
    title: { size: 16, lineHeight: 22, weight: 500 },
    subtitle: { size: 12, lineHeight: 16, weight: 400 },
    subtitleTop: 2,
    action: { size: 14, lineHeight: 20, weight: 500 },
    actionTop: 8,
    topRatio: 0.45,
    unboundedPaddingV: 48,
  },
  topBar: {
    height: 52,
    paddingH: 16,
    buttonSize: 40,
    buttonGap: 8,
    textButtonMinWidth: 60,
    textButtonPaddingH: 12,
    titleGap: 10,
    blurDistance: 30,
    iconSize: 24,
    largeTitleHeight: 110,
    largeTitleSize: 32,
    largeTitleCollapsedSize: 24,
    largeTitleWeight: 600,
    largeTitleCenter: 72.5,
    largeTitleSnap: { bounce: 0, response: 0.25 },
  },
  panel: {
    cornerRadius: 45,
    cornerRadiusNoSmooth: 32,
    cornerWeight: 3,
    handleWidth: 36,
    handleHeight: 4,
    handleTop: 12,
    handleAreaHeight: 24,
    topMin: 40,
    dragDamping: 0.2,
    dragMax: 28,
    dismissVelocity: 500,
    settle: { bounce: 0, response: 0.4 },
    enterResponseMin: 0.25,
    enterResponseMax: 0.45,
    exitResponseMin: 0.18,
    exitResponseMax: 0.37,
  },
  checkbox: {
    iconSize: 24,
    boxUnchecked: 16.4,
    stroke: 1.3,
    radiusUnchecked: 3.2,
    boxChecked: 18,
    radiusChecked: 4,
    markStroke: 1.3,
    dashWidth: 10,
    dashHeight: 1.6,
    textGap: 8,
    uncheckedColor: { light: '#00000042', dark: '#FFFFFF4D' },
    uncheckedDisabled: { light: '#00000014', dark: '#FFFFFF26' },
    mark: '#FFFFFFFF',
    markDisabled: { light: '#FFFFFF8A', dark: '#FFFFFF29' },
    duration: 300,
    scalePeak: 1.08,
  },
  chip: {
    height: 28,
    heightLarge: 32,
    textSize: 12,
    textSizeLarge: 14,
    paddingH: 12,
    minWidth: 52,
    maxWidth: 300,
    gap: 8,
    bg: { light: '#00000014', dark: '#FFFFFF26' },
    text: { light: '#000000E6', dark: '#FFFFFFE6' },
    selectedText: '#FFFFFFFF',
    disabledBg: { light: '#00000014', dark: '#FFFFFF1A' },
    disabledText: { light: '#00000042', dark: '#FFFFFF29' },
    disabledSelectedText: { light: '#FFFFFF8A', dark: '#FFFFFF29' },
    iconSize: 16,
    iconGap: 4,
    colorSpring: { bounce: 0, response: 0.3 },
  },
  segment: {
    height: 40,
    heightTiny: 32,
    minSegmentWidth: 52,
    paddingH: 12,
    textSize: 14,
    textWeight: 500,
    indicatorInset: 4,
    indicatorInsetTiny: 2,
    bg: { light: '#0000000F', dark: '#FFFFFF1F' },
    indicator: { light: '#FFFFFFB2', dark: '#FFFFFF33' },
    shadowOffset: 2,
    shadow: { light: '#0000000D', dark: '#00000014' },
    move: { bounce: 0.1, response: 0.4 },
    dip: { bounce: 0.5, response: 0.6 },
    dipMin: 0.9,
    rubber: { bounce: 0, response: 0.6 },
    rubberCoef: 0.12,
    switchDistance: 5,
    indicatorHitSlopPx: 10,
    extraWidth: 7,
    extraWidthTiny: 5,
    widthResponse: 0.6,
    widthResponseMin: 0.4,
    widthBounce: 0.5,
    widthBounceMin: 0.1,
    widthVelocity: 1000,
    heightVelocity: -500,
  },
  seekBar: {
    trackHeight: 20,
    pressedScale: 1.4,
    thumbRadius: 6,
    thumbRadiusPressed: 8,
    paddingH: 14,
    thumbShadowRadius: 4,
    thumbShadowY: 2,
    thumbShadow: { light: '#0000001A', dark: '#00000040' },
    track: { light: '#0000001F', dark: '#FFFFFF33' },
    thumb: '#FFFFFFFF',
    thumbDisabled: { light: '#FFFFFF8A', dark: '#FFFFFF29' },
    trackSpring: { bounce: 0, response: 0.5 },
    thumbGrow: { bounce: 0.3, response: 0.5 },
    thumbShrink: { bounce: 0, response: 0.5 },
    jump: { bounce: 0, response: 0.3 },
    follow: { bounce: 0, response: 0.15 },
    flingMin: 100,
    flingMax: 8000,
    flingDamping: 15,
  },
  input: {
    textSize: 15,
    paddingV: 15,
    hintFloatSize: 10,
    hintTop: 12,
    line: { light: '#0000001F', dark: '#FFFFFF33' },
    lineDisabled: { light: '#00000019', dark: '#FFFFFF19' },
    lineFocusWidth: 1,
    focusDuration: 250,
    hintDuration: 200,
    textDisabled: { light: '#00000042', dark: '#FFFFFF4D' },
    errorTextSize: 10,
    errorGap: 4,
    errorColorDuration: 217,
    shakeAmplitude: 5.33,
    shakeDuration: 450,
    clearSize: 22,
    clearGap: 8,
  },
  progress: {
    barHeight: 4,
    track: { light: '#0000001F', dark: '#FFFFFF33' },
    ringTrack: { light: '#0080FF26', dark: '#1A8CFF40' },
    ringSmall: 18,
    ringSmallStroke: 2.67,
    ringLarge: 26,
    ringLargeStroke: 3.33,
    spinDuration: 1000,
    arcMin: 60,
    arcMax: 120,
  },
  snackBar: {
    bg: { light: '#FFFFFFFF', dark: '#333333FF' },
    textSize: 14,
    textWeight: 500,
    paddingH: 16,
    paddingV: 10,
    multiLineRadius: 16,
    actionMaxWidth: 110,
    marginBottom: 88,
    marginBottomSmall: 64,
    shadowElevation: 26,
    shadowColor: '#000000EE',
    enter: { bounce: 0, response: 0.3 },
    exit: { bounce: 0, response: 0.25 },
    scaleFrom: 0.8,
    duration: 2500,
  },
  redDot: {
    dot: 6,
    height: 16,
    width1: 16,
    width2: 20,
    width3: 26,
    bg: { light: '#EB3B2FFF', dark: '#EB493DFF' },
    text: '#FFFFFFFF',
    textSize: 10,
    duration: 520,
  },
  stepper: {
    buttonSize: 32,
    buttonBg: { light: '#00000014', dark: '#FFFFFF1A' },
    iconStroke: 1.6,
    iconSize: 14,
    numberSize: 18,
    numberMinWidth: 44,
    numberGap: 12,
    repeat: 100,
  },
  toolTip: {
    bg: { light: '#0080FFFF', dark: '#1A8CFFFF' },
    text: '#FFFFFFFF',
    padding: 13,
    radius: 17,
    cornerWeight: 3,
    screenMargin: 16,
    arrowWidth: 20,
    arrowHeight: 10,
    arrowTipRadius: 2,
    arrowEmbed: 0.33,
    shadowElevation: 24,
    shadowColor: '#000000E0',
    enterScale: { bounce: 0.2, response: 0.4 },
    enterAlpha: { bounce: 0.2, response: 0.3 },
    exitDuration: 320,
  },
  picker: {
    rowHeight: 45,
    rows: 3,
    textSize: 16,
    selectedTextSize: 20,
    textWeight: 500,
    color: { light: '#00000042', dark: '#FFFFFF4D' },
    selectedColor: { light: '#000000FF', dark: '#FFFFFFE6' },
    bandHalf: 24,
    lineInset: 16,
    line: { light: '#0000001F', dark: '#FFFFFF33' },
    flingScale: 1.6,
    flingMin: 750,
    flingMax: 5000,
    flingDurationScale: 1.5,
    snapDuration: 300,
    minWidth: 64,
  },
  fab: {
    size: 56,
    iconSize: 24,
    iconStroke: 2,
    disabledBg: { light: '#B2D8FFFF', dark: '#3D6082FF' },
    labelGap: 12,
    itemFirstGap: 32,
    itemGap: 16,
    labelTextSize: 12,
    labelPaddingH: 8,
    labelPaddingV: 4,
    labelMaxWidth: 220,
    labelText: '#FFFFFFFF',
    rotation: 45,
    rotateDuration: 300,
    itemDuration: 300,
    itemStagger: 50,
    itemScaleFrom: 0.6,
    itemSpring: { bounce: 0.2, response: 0.28 },
    showDuration: 350,
  },
} as const;

export type CoTokensTree = typeof CoTokens;
